-- ============================================================================
-- HİZMET BİNALARI IMPORT
-- Her departman için bir hizmet binası oluşturulur
-- ============================================================================
USE SGKPortalDB;
GO

PRINT '📦 Hizmet Binaları import ediliyor...';
GO

SET IDENTITY_INSERT CMN_HizmetBinalari ON;
GO

-- ID=1 zaten SEED_DATA_FIXED.sql ile eklendi (İL MÜDÜRLÜĞÜ)

IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 2) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (2, N'KONAK SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 3) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (3, N'BAYRAKLI SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 4) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (4, N'KARŞIYAKA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 5) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (5, N'BUCA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 7) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (7, N'BERGAMA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 8) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (8, N'MENEMEN SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 9) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (9, N'ALİAĞA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 10) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (10, N'ÇİĞLİ SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 11) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (11, N'KEMALPAŞA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 12) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (12, N'ÖDEMİŞ SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 13) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (13, N'TORBALI SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 14) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (14, N'TİRE SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 15) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (15, N'BAYINDIR SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 16) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (16, N'GAZİEMİR SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 17) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (17, N'KARABAĞLAR SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 18) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (18, N'URLA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 19) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (19, N'ÇEŞME SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 20) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (20, N'BALÇOVA SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 21) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (21, N'MENDERES SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 22) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (22, N'BORNOVA NACİ ŞAHİN SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 23) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (23, N'ALSANCAK SAĞLIK SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 24) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (24, N'KEMERALTI SAĞLIK SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 25) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (25, N'KORDON SAĞLIK SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 26) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (26, N'REHBERLİK VE TEFTİŞ GRUP BAŞKANLIĞI', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 30) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (30, N'-BELİRTİLMEMİŞ-', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 33) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (33, N'DİĞER/İL DIŞI/MİSAFİR', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 34) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (34, N'HASAN TAHSİN SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 35) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (35, N'MALİ HİZMETLER SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 36) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (36, N'SOSYAL TESİSLER', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 38) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (38, N'SELÇUK SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 39) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (39, N'SEFERİHİSAR SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM CMN_HizmetBinalari WHERE HizmetBinasiId = 40) INSERT INTO CMN_HizmetBinalari (HizmetBinasiId, HizmetBinasiAdi, Adres, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (40, N'DOKUZ EYLÜL SOSYAL GÜVENLİK MERKEZİ', N'İzmir', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
GO

SET IDENTITY_INSERT CMN_HizmetBinalari OFF;
GO

PRINT '✅ 31 Hizmet Binası import edildi (ID=1 zaten SEED_DATA_FIXED.sql ile eklendi)';
PRINT '✅ Her departman için bir hizmet binası oluşturuldu (ID eşleşmesi korundu)';
GO
