-- ============================================================================
-- SERVİSLER IMPORT - PART 1 (ID: 1-80)
-- ============================================================================
USE SGKPortalDB;
GO

PRINT '📦 Servisler import ediliyor (Part 1)...';
GO

SET IDENTITY_INSERT PER_Servisler ON;
GO

IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 2) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (2, N'BAĞ-KUR LOJMANLARI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 3) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (3, N'BİLGİ-İŞLEM SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 4) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (4, N'SAĞLIK KURULU BÜRO İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 5) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (5, N'DESTEK HİZMETLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 6) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (6, N'DESTEK HİZMETLERİ SERVİSİ-1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 8) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (8, N'DESTEK HİZMETLERİ SERVİSİ-3', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 9) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (9, N'DESTEK HİZMETLERİ SERVİSİ-4', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 11) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (11, N'KAMU EMEKLİ AYLIKLARI SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 12) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (12, N'EMEKLİLİK SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 13) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (13, N'EMEKLİLİK SERVİSİ- 1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 14) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (14, N'EMEKLİLİK SERVİSİ- 2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 15) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (15, N'EMEKLİLİK SERVİSİ- 3', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 17) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (17, N'TAKİP SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 18) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (18, N'GELEN EVRAK KAYIT SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 19) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (19, N'GELİR MUHASEBE SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 20) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (20, N'GENEL SAĞLIK SİGORTALISI ÖDEME SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 21) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (21, N'GİDEN EVRAK KAYIT SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 22) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (22, N'GİDER MUHASEBE SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 23) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (23, N'GRUP BAŞKANLIĞI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 24) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (24, N'HUKUK SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 25) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (25, N'HALKLA İLİŞKİLER SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 26) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (26, N'HALKLA İLİŞKİLER VE BİLGİLENDİRME SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 27) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (27, N'İCRA TAKİP, HACİZ VE SATIŞ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 28) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (28, N'İCRA TAKİP, HACİZ VE SATIŞ SERVİSİ-2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 29) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (29, N'İCRA TAKİP, HACİZ VE SATIŞ SERVİSİ-3', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 31) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (31, N'İCRA TAKİP, HACİZ VE SATIŞ SERVİSİ-1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 32) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (32, N'İŞYERİ TESCİL VE E-SİGORTA SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 33) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (33, N'İDARE', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 34) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (34, N'İNŞAAT EMLAK SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 35) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (35, N'PERSONEL SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 36) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (36, N'İDARE-2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 37) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (37, N'İZMİR ESNAF VE SANATKARLAR', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 38) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (38, N'KADİM SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 39) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (39, N'KISA VADELİ SİGORTALI SERVİSİ-2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 41) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (41, N'KISA VADELİ SİGORTALI SERVİSİ-1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 44) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (44, N'KURUM HEKİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 46) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (46, N'ÖZEL KALEM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 47) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (47, N'DİSİPLİN BİRİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 48) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (48, N'PRİM TAHAKKUK VE TAHSİLAT SERVİSİ-3', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 49) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (49, N'PRİM TAHAKKUK VE TAHSİLAT SERVİSİ-2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 50) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (50, N'PRİM TAHAKKUK VE TAHSİLAT SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 51) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (51, N'PRİM TAHAKKUK VE TAHSİLAT SERVİSİ-4', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 52) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (52, N'PRİM TAHAKKUK VE TAHSİLAT SERVİSİ-1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 53) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (53, N'SAĞLIK HİZMET SUNUCULARI ÖDEME SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 55) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (55, N'SAĞLIK HİZMET SUNUCULARI SÖZLEŞME SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 56) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (56, N'SAĞLIK HİZMET SUNUCULARI DENETİM SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 58) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (58, N'SİGORTALI TESCİL VE HİZMET SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 59) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (59, N'SOSYAL GÜVENLİK DENETMENLİK SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 60) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (60, N'SİGORTALI TESCİL VE HİZMET SERVİSİ-3', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 61) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (61, N'SİGORTALI TESCİL VE HİZMET SERVİSİ-1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 63) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (63, N'SİGORTALI TESCİL VE HİZMET SERVİSİ-2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 66) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (66, N'ULAŞIM SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 67) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (67, N'DESTEK HİZMETLERİ SERVİSİ - 2 (TABLDOT SERVİSİ)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 68) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (68, N'YURTDIŞI EMEKLİLİK İLK KARAR SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 69) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (69, N'ARŞİV', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 70) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (70, N'-BELİRTİLMEMİŞ-', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 71) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (71, N'SİGORTALI TESCİL VE HİZMET SERVİSİ-4', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 72) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (72, N'İL DIŞI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 73) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (73, N'EĞİTİM VE DİNLENME TESİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 74) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (74, N'ARGE ve İSTATİSTİK', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 75) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (75, N'ASGARİ İŞÇİLİK TESPİT KOMİSYONU BİRİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 76) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (76, N'MİSAFİR', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 77) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (77, N'İZLEME VE DEĞERLENDİRME BİRİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 78) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (78, N'İNCELEME VE KONTROL BİRİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
GO

SET IDENTITY_INSERT PER_Servisler OFF;
GO

PRINT '✅ Part 1 tamamlandı (ID: 2-78, 58 servis)';
GO
