-- ============================================================================
-- SERVİSLER IMPORT - PART 2 (ID: 113-172)
-- ============================================================================
USE SGKPortalDB;
GO

PRINT '📦 Servisler import ediliyor (Part 2)...';
GO

SET IDENTITY_INSERT PER_Servisler ON;
GO

IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 113) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (113, N'YURTDIŞI BORÇLANMA VE YAZIŞMA SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 114) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (114, N'4B KOMİSYON', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 115) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (115, N'EMEKLİLİK SERVİSİ- 4', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 116) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (116, N'İŞ KAZALARI TESPİT KOMİSYONU', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 119) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (119, N'GÜMÜŞPALA ARŞİV', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 121) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (121, N'EĞİTİM ARAŞTIRMA VE GELİŞTİRME SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 122) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (122, N'DENETİM RAPORLARI DEĞERLENDİRME SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 123) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (123, N'TARIM TEVKİFAT SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 125) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (125, N'ÖĞRENCİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 126) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (126, N'İDARİ-1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 128) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (128, N'TÜM İŞ VE İŞLEMLER', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 129) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (129, N'EVDE ÇOCUK BAKIM BÜROSU', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 130) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (130, N'RÜCU İŞLEMLERİ ALT SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 133) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (133, N'MOBİL SGM ARAÇ 1', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 134) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (134, N'MOBİL SGM ARAÇ 2', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 136) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (136, N'BUCA YERLEŞKESİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 137) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (137, N'4B 2. KARAR İŞLEMLERİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 138) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (138, N'SANTRAL', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 139) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (139, N'YURTDIŞI REHBERLİK SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 140) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (140, N'HAK SAHİPLİĞİ SORGULAMA VE BORÇ GİRİŞ BİRİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 141) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (141, N'PERFORMANS YÖNETİMİ VE KOORDİNASYON SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 142) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (142, N'PERFORMANS YÖNETİMİ VE KOORDİNASYON-1 SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 156) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (156, N'TAKİP VE KOORDİNASYON BİRİMİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 157) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (157, N'EMEKLİLİK SERVİSİ- 5 (4-A ÖLÜM AYLIĞI İŞLEMLERİ SERVİSİ)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 158) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (158, N'EMEKLİLİK SERVİSİ- 6 (4-A ÖLÜM AYLIĞI İKİNCİ KARAR İŞLEMLERİ SERVİSİ)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 159) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (159, N'4/B SİGORTALI TESCİL VE HİZMET SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 160) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (160, N'ARŞİV TARAMA SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 161) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (161, N'YURTDIŞI SAĞLIK SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 162) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (162, N'EMEKLİLİK SERVİSİ- 7', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 163) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (163, N'EMEKLİLİK SERVİSİ-11', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 164) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (164, N'4/A YAŞLILIK İLK KARAR İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 165) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (165, N'4/A YAŞLILIK İKİNCİ KARAR İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 166) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (166, N'4/A EMEKLİ KONTROL MUAYENE İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 167) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (167, N'4/A YAŞLILIK AYLIĞI DENETİM RAPORLARI DEĞERLENDİRME VE EYT İKİNCİ KARAR İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 168) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (168, N'4/A İŞ KAZASI GELİR BAĞLAMA İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 169) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (169, N'4/A ÖLÜM AYLIĞI İLK KARAR İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 170) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (170, N'4/A ÖLÜM AYLIĞI İKİNCİ KARAR İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 171) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (171, N'4/B İLK KARAR İŞLEMLERİ SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Servisler WHERE ServisId = 172) INSERT INTO PER_Servisler (ServisId, ServisAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (172, N'YURTDIŞI EMEKLİLİK İKİNCİ KARAR SERVİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
GO

SET IDENTITY_INSERT PER_Servisler OFF;
GO

PRINT '✅ Part 2 tamamlandı (ID: 113-172, 47 servis)';
PRINT '✅ Toplam 105 servis import edildi (ID=1 zaten SEED_DATA_FIXED.sql ile eklendi)';
GO
