-- ============================================================================
-- ÜNVANLAR IMPORT (unvanlar.sql'den)
-- ============================================================================
USE SGKPortalDB;
GO

PRINT '📦 Ünvanlar import ediliyor...';
GO

SET IDENTITY_INSERT PER_Unvanlar ON;
GO

IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 2) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (2, N'BÜRO PERSONELİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 3) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (3, N'V.H.K.İ.', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 4) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (4, N'UZMAN TABİP', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 5) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (5, N'ŞEF', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 6) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (6, N'AVUKAT', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 7) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (7, N'SG İL MÜDÜR YARDIMCISI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 8) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (8, N'MÜHENDİS', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 9) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (9, N'SG İL MÜDÜRÜ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 10) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (10, N'ECZACI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 11) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (11, N'TEKNİSYEN', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 12) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (12, N'ÇOCUK GELİŞİMCİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 13) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (13, N'TABİP', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 14) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (14, N'HİZMETLİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 15) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (15, N'MUHASEBE YETKİLİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 16) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (16, N'HEMŞİRE', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 17) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (17, N'AŞÇI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 18) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (18, N'DAĞITICI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 19) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (19, N'BEKÇİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 20) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (20, N'ELEKTRONİK MÜHENDİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 21) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (21, N'MUHASEBECİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 22) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (22, N'SG DENETMENİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 23) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (23, N'ŞOFÖR', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 24) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (24, N'MİMAR', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 25) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (25, N'MMY', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 26) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (26, N'SSGM MÜDÜRÜ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 27) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (27, N'SGMM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 28) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (28, N'İCRA MEMURU', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 29) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (29, N'DİŞ TABİBİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 30) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (30, N'İŞÇİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 31) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (31, N'-BELİRTİLMEMİŞ-', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 32) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (32, N'KORUMA VE GÜVENLİK', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 33) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (33, N'BİYOLOG', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 34) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (34, N'LABORANT', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 35) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (35, N'BÖLGE MÜDÜR YARDIMCISI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 36) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (36, N'ŞUBE MÜDÜRÜ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 37) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (37, N'TEKNİKER', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 38) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (38, N'DİNLENME VE BAKIM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 39) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (39, N'SOSYAL ÇALIŞMACI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 40) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (40, N'MAKİNE MÜHENDİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 41) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (41, N'PROGRAMCI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 42) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (42, N'VEZNEDAR', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 43) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (43, N'ARAŞTIRMACI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 44) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (44, N'UZMAN', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 45) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (45, N'SAĞLIK TEKNİSYENİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 46) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (46, N'PSİKOLOG', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 47) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (47, N'SAĞLIK MEMURU', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 48) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (48, N'SAĞLIK TEKNİKER', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 49) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (49, N'FİZYOTERAPİST', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 50) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (50, N'SGMMY', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 51) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (51, N'ÇÖZÜMLEYİCİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 52) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (52, N'SG DENETMEN YRD.', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 53) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (53, N'BAĞKUR İL MD. YRD.', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 54) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (54, N'MUHASEBE YETKİLİSİ YRD.', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 55) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (55, N'SÜRVEYAN', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 56) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (56, N'SOSYAL TESİS YÖNETİCİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 57) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (57, N'SSGMMY', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 58) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (58, N'SOSYAL TESİS YÖNETİCİSİ YARDIMCISI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 59) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (59, N'GEÇİCİ PERSONEL', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 60) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (60, N'KİMYAGER', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 61) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (61, N'ŞEHİR PLANCISI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 62) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (62, N'BİLGİSAYAR İŞLETMENİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 63) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (63, N'YRD. TEKN. PER. (ELEKTRİK TEKN.)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 64) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (64, N'YRD. TEKN. PER. (MARANGOZ)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 65) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (65, N'YRD. TEKN. PER. (İNŞAAT)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 66) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (66, N'YRD. TEKN. PER. (SIHHİ TESİSAT)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 67) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (67, N'YRD. TEKN. PER. (KLİMA TESİSAT)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 68) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (68, N'YRD. TEKN. PER. (KALORİFERCİ)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 69) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (69, N'YRD. TEKN. PER. (BOYACI)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 70) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (70, N'YRD. TEKN. PER. (KLİMA)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 71) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (71, N'SÜREKLİ İŞÇİ (ŞOFÖR)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 72) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (72, N'SÜREKLİ İŞÇİ (ŞOFÖR KOORDİNATÖR)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 73) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (73, N'GÜVENLİK PERSONELİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 74) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (74, N'GÜVENLİK PERSONELİ (KOORDİNATÖR)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 75) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (75, N'TEMİZLİK GÖREVLİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 76) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (76, N'TEMİZLİK GÖREVLİSİ (KOORDİNATÖR)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 77) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (77, N'İDARİ BÜRO GÖREVLİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 78) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (78, N'SÜREKLİ İŞÇİ (KURUM DIŞINDAN GÖREVLENDİRME)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 80) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (80, N'SÜREKLİ İŞÇİ (TEKNİK ELEMAN)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 81) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (81, N'MALİ HİZMETLER UZMANI', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 83) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (83, N'DESTEK PERSONELİ (TEMİZLİK)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 84) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (84, N'TEKNİSYEN (ELEKTRİK VE ELEKTRONİK)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 86) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (86, N'SORUMLU İCRA MEMURU', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 87) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (87, N'ŞEF V.', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 88) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (88, N'KORUMA VE GÜVENLİK GÖREVLİSİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 89) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (89, N'AŞÇI (SÖZLEŞMELİ)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 91) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (91, N'STAJYER ÖĞRENCİ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Unvanlar WHERE UnvanId = 92) INSERT INTO PER_Unvanlar (UnvanId, UnvanAdi, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (92, N'GEÇİCİ İŞÇİ (İUP)', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
GO

SET IDENTITY_INSERT PER_Unvanlar OFF;
GO

PRINT '✅ 88 Ünvan import edildi (ID=1 zaten SEED_DATA_FIXED.sql ile eklendi)';
GO
