-- ============================================================================
-- DEPARTMANLAR IMPORT (birim.sql'den)
-- ============================================================================
USE SGKPortalDB;
GO

PRINT '📦 Departmanlar import ediliyor...';
GO

SET IDENTITY_INSERT PER_Departmanlar ON;
GO

IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 2) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (2, N'KONAK SOSYAL GÜVENLİK MERKEZİ', N'KONAK SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 3) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (3, N'BAYRAKLI SOSYAL GÜVENLİK MERKEZİ', N'BAYRAKLI SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 4) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (4, N'KARŞIYAKA SOSYAL GÜVENLİK MERKEZİ', N'KARŞIYAKA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 5) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (5, N'BUCA SOSYAL GÜVENLİK MERKEZİ', N'BUCA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 7) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (7, N'BERGAMA SOSYAL GÜVENLİK MERKEZİ', N'BERGAMA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 8) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (8, N'MENEMEN SOSYAL GÜVENLİK MERKEZİ', N'MENEMEN SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 9) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (9, N'ALİAĞA SOSYAL GÜVENLİK MERKEZİ', N'ALİAĞA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 10) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (10, N'ÇİĞLİ SOSYAL GÜVENLİK MERKEZİ', N'ÇİĞLİ SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 11) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (11, N'KEMALPAŞA SOSYAL GÜVENLİK MERKEZİ', N'KEMALPAŞA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 12) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (12, N'ÖDEMİŞ SOSYAL GÜVENLİK MERKEZİ', N'ÖDEMİŞ SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 13) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (13, N'TORBALI SOSYAL GÜVENLİK MERKEZİ', N'TORBALI SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 14) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (14, N'TİRE SOSYAL GÜVENLİK MERKEZİ', N'TİRE SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 15) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (15, N'BAYINDIR SOSYAL GÜVENLİK MERKEZİ', N'BAYINDIR SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 16) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (16, N'GAZİEMİR SOSYAL GÜVENLİK MERKEZİ', N'GAZİEMİR SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 17) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (17, N'KARABAĞLAR SOSYAL GÜVENLİK MERKEZİ', N'KARABAĞLAR SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 18) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (18, N'URLA SOSYAL GÜVENLİK MERKEZİ', N'URLA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 19) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (19, N'ÇEŞME SOSYAL GÜVENLİK MERKEZİ', N'ÇEŞME SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 20) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (20, N'BALÇOVA SOSYAL GÜVENLİK MERKEZİ', N'BALÇOVA SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 21) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (21, N'MENDERES SOSYAL GÜVENLİK MERKEZİ', N'MENDERES SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 22) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (22, N'BORNOVA NACİ ŞAHİN SOSYAL GÜVENLİK MERKEZİ', N'BORNOVA N.ŞAHİN SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 23) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (23, N'ALSANCAK SAĞLIK SOSYAL GÜVENLİK MERKEZİ', N'ALSANCAK SSGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 24) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (24, N'KEMERALTI SAĞLIK SOSYAL GÜVENLİK MERKEZİ', N'KEMERALTI SSGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 25) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (25, N'KORDON SAĞLIK SOSYAL GÜVENLİK MERKEZİ', N'KORDON SSGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 26) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (26, N'REHBERLİK VE TEFTİŞ GRUP BAŞKANLIĞI', N'TEFTİŞ GRUP', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 30) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (30, N'-BELİRTİLMEMİŞ-', N'-BELİRTİLMEMİŞ-', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 33) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (33, N'DİĞER/İL DIŞI/MİSAFİR', N'DİĞER/İL DIŞI/MİSAFİR', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 34) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (34, N'HASAN TAHSİN SOSYAL GÜVENLİK MERKEZİ', N'HASAN TAHSİN SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 35) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (35, N'MALİ HİZMETLER SOSYAL GÜVENLİK MERKEZİ', N'MALİ HİZMETLER MÜDÜRLÜĞÜ', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 36) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (36, N'SOSYAL TESİSLER', N'SOSYAL TESİSLER', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 38) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (38, N'SELÇUK SOSYAL GÜVENLİK MERKEZİ', N'SELÇUK SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 39) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (39, N'SEFERİHİSAR SOSYAL GÜVENLİK MERKEZİ', N'SEFERİHİSAR SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
IF NOT EXISTS (SELECT 1 FROM PER_Departmanlar WHERE DepartmanId = 40) INSERT INTO PER_Departmanlar (DepartmanId, DepartmanAdi, DepartmanAdiKisa, Aktiflik, EkleyenKullanici, EklenmeTarihi, DuzenleyenKullanici, DuzenlenmeTarihi) VALUES (40, N'DOKUZ EYLÜL SOSYAL GÜVENLİK MERKEZİ', N'DOKUZ EYLÜL SGM', 0, 'IMPORT', GETDATE(), 'IMPORT', GETDATE());
GO

SET IDENTITY_INSERT PER_Departmanlar OFF;
GO

PRINT '✅ 31 Departman import edildi (ID=1 zaten SEED_DATA_FIXED.sql ile eklendi)';
GO
